---
title: "Riddler 2018-08-10: Where on Earth is the Riddler?"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(dplyr)
library(magrittr)
library(ggplot2)
```

[Link to Riddler](https://fivethirtyeight.com/features/where-on-earth-is-the-riddler/)

___

## Riddler Express

From 538:

> Describe where on Earth from which you can travel one mile south, then one mile east and then one mile north and arrive at your original location.

**Solution:** The two locations that this is possible are the **North Pole** and the **somewhere slightly north of the South Pole**. 

To see why this is the case, let's first look at the North Pole: When you travel south one mile, then move laterally eastward, moving north one mile will make you return right to your beginning area, the North Pole.

Now, for the area just slightly north of the South Pole: We want to find a starting location that is on the latitude that is one mile north of the latitude where the circumference (cross section) of the earth is 1 mile. To see how this works, you first travel one mile south from the starting location. Next you travel eastward along this one-mile circumference, completing exactly one circumnavigation of the earth at that latitude, ending up in the exact same spot. Lastly, going one mile north will return you to the same spot. Because this method will work along any area at the same starting latitude, then there are an infinite amount of points that you can start from.

___

___
