---
title: "Riddler 2018-11-02: How Far Would You Go To Rig A Coin Flip? "
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(dplyr)
library(magrittr)
library(ggplot2)
library(ggthemes)
```

**[Link to Riddler](https://fivethirtyeight.com/features/how-far-would-you-go-to-rig-a-coin-flip/)**

___

## Riddler Express

From 538:

> Coin flips are a handy way to determine a winner — if the goal is to give two people an equal chance of winning. But sometimes it’s not. Suppose Anna and Barry aren’t interested in equity. All they have is a fair coin marked heads and tails. How can they devise a game that gives Anna a 1 in 3 chance of winning? What about a 1 in 4 chance? What about a 1 in 5 chance?

### Solution 

* **1/3 Chance**: Flip the coin twice. If both coins are head, then Anna wins. If there is one head and one tails, then Barry wins. If both coins are tails, then flip coin twice again.
* **1/4 Chance**: Flip coin twice. If both coins are head, then Anna wins. In all other scenarios, Barry wins.
* **1/5 Chance**: Flip coin three times. If all three coins are head, then Anna wins. If coin has two heads (which happens with probability 3/8), then flip coin again three times. Barry wins in all other scenarios.



